server:
  port: 8081
  servlet:
    context-path: /api

dubbo:
  application:
    name: ddd-demo-application
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: dubbo
    port: -1

spring:
  data:
    redis:
      redisson:
        address: redis://localhost:6379

logging:
  level:
    root: info
    sql: debug